using Microsoft.AspNetCore.Mvc;
using Presentation.Models;
using Presentation.Services;

namespace Presentation.Controllers;

// Generated by Chat GPT 4.o
[ApiController]
[Route("api/contactinfo")]
public class ContactInfoController(ContactInfoService service) : ControllerBase
{
    private readonly ContactInfoService _service = service;

    [HttpPost]
    public async Task<IActionResult> Add(ContactInfoRequest request)
    {
        var result = await _service.AddContactInfoAsync(request);
        if (result)
            return Ok("Kontaktinfo sparad.");
        return BadRequest("Kunde inte spara kontaktinfo.");
    }
}

